In [13]:
#import 
import pandas as pd
import os
import csv

In [14]:
#path to CSV file
globes= os.path.join("C:/Users/kyran/Documents/Netflix_Presents_Golden_Globe_Winners/golden_globe_awards.csv")

In [15]:
#read CSV file
globes = pd.read_csv(globes)

#print csv file
globes.head()

,year_film,year_award,ceremony,category,nominee,title,win
0,1943,1944,1,Best Performance by an Actress in a Supporting...,Katina Paxinou,For Whom The Bell Tolls,True
1,1943,1944,1,Best Performance by an Actor in a Supporting R...,Akim Tamiroff,For Whom The Bell Tolls,True
2,1943,1944,1,Best Director - Motion Picture,Henry King,The Song Of Bernadette,True
3,1943,1944,1,Picture,The Song Of Bernadette,NaN,True
4,1943,1944,1,Actress In A Leading Role,Jennifer Jones,The Song Of Bernadette,True

In [16]:
#inspect data types in df
globes.dtypes

year_film      int64
year_award     int64
ceremony       int64
category      object
nominee       object
title         object
win             bool
dtype: object

In [17]:
#fill the NaN values in title column with the value from the nominee column
globes.loc[globes["title"].isnull(), 'title']= globes["nominee"]
globes.head()

,year_film,year_award,ceremony,category,nominee,title,win
0,1943,1944,1,Best Performance by an Actress in a Supporting...,Katina Paxinou,For Whom The Bell Tolls,True
1,1943,1944,1,Best Performance by an Actor in a Supporting R...,Akim Tamiroff,For Whom The Bell Tolls,True
2,1943,1944,1,Best Director - Motion Picture,Henry King,The Song Of Bernadette,True
3,1943,1944,1,Picture,The Song Of Bernadette,The Song Of Bernadette,True
4,1943,1944,1,Actress In A Leading Role,Jennifer Jones,The Song Of Bernadette,True

In [19]:
#convert title column values to uppercase
globes['title'] = globes['title'].str.upper()
globes.head()

,year_film,year_award,ceremony,category,nominee,title,win
0,1943,1944,1,Best Performance by an Actress in a Supporting...,Katina Paxinou,FOR WHOM THE BELL TOLLS,True
1,1943,1944,1,Best Performance by an Actor in a Supporting R...,Akim Tamiroff,FOR WHOM THE BELL TOLLS,True
2,1943,1944,1,Best Director - Motion Picture,Henry King,THE SONG OF BERNADETTE,True
3,1943,1944,1,Picture,The Song Of Bernadette,THE SONG OF BERNADETTE,True
4,1943,1944,1,Actress In A Leading Role,Jennifer Jones,THE SONG OF BERNADETTE,True

In [23]:
#save as CSV file
globes.to_csv('globes_transformed.csv', index= True)

PermissionError: [Errno 13] Permission denied: 'globes_transformed.csv'